version: "3.8"

services:

  login:
    image: openjdk:19
    container_name: loginimage
    ports:
      - 8081:8080
    expose:
      - "8081"
    depends_on:
      - login-db
    networks:
      - login-net
#      - smartcitywastemanagement_main-net
    volumes:
      - ./build/libs/login-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar
  login-db:
    image: mongo:5.0
    container_name: mongodbimage1
    ports:
      - 27018:27017
    networks:
      - login-net
networks:
  login-net:
    driver:
      "bridge"
#  smartcitywastemanagement_main-net:
#    driver:
#      "bridge"
#    external: true

