name: Java CI with Gradle

on:
	push:
		branches:
			- admin
    pull_request:
        branches:
        	- admin

jobs:
	build:
		runs-on: ubuntu-latest
		
		steps:
		- name: Check out code
		  uses: actions/checkout@v2
		  
		- name: Set up JDK 19
		  uses: actions/setup-java@v2 
		  with:
		  	java-version: 19
		
		- name: Build with Gradle
		  run: ./gradlew build