version: "3.8"

services:

  pagare:
    image: openjdk:19
    container_name: pagareimage
    ports:
      - 8082:8080
    expose:
      - "8082"
    depends_on:
      - pagare-db
    networks:
      - pagare-net
      - smartcitywastemanagement_main-net
    volumes:
      - ./build/libs/pagare-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar
  pagare-db:
    image: mongo:5.0
    container_name: mongodbimage2
    ports:
      - 27019:27017
    networks:
      - pagare-net
networks:
  pagare-net:
    driver:
      "bridge"
  smartcitywastemanagement_main-net:
    driver:
      "bridge"
    external: true
