name: Java CI with Gradle
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - admin, login, checking, simulazione, giudizio, monitoraggio, emissione, pagare

  pull_request:
    branches:
      - admin, login, checking, simulazione, giudizio, monitoraggio, emissione, pagare

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
